name: heat_map_package
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  dartz: ^0.10.1
  string_validator: ^0.3.0
  dio: 
  #dio: ^4.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  modular_test: ^2.0.0
  mocktail:
  #mocktail: ^0.2.0


flutter:
